### ISSUE TITLE
rendered version?

### ISSUE THREAD

**Issue by anarcat** [swaywm/sway-protocols#5]
Hi!

This repository is linked from the [sway homepage](http://swaywm.org/) yet it only contains a raw XML document which, while actually readable, is not exactly user-friendly. Is there a (HTML?) rendered version of the document somewhere that could be a little more readable?

or am I misunderstanding the point of this repository? :)

**Comment by SirCmpwn** [comment]
This is not an end-user concern. The sort of people this repository is relevant to are comfortable reading XML.

**Comment by anarcat** [comment]
thanks for the clarification, and sorry for the noise!
